## 3주차 실습 수업 모범 답안

### 배열 생성

In [1]:
# 사용할 라이브러리 가져오기
import numpy as np
import time
from numpy.random import rand, normal, randint

In [2]:
#1)
x = 10
random_number = rand(x)
print(random_number)

[0.93545546 0.3846934  0.59288447 0.1476344  0.66362987 0.71285068
 0.8490949  0.22020764 0.64199014 0.8023674 ]


In [3]:
#2)
x = 1
y = 1000
z = (2,5)  # 2 rows x 5 columns 행렬
np.random.seed(12345)
A = randint(x,y,z)
print(f'A\n{A}')

A
[[483 486 286 130 421]
 [426 383 358 547 542]]


In [4]:
#2-1)
print(f'np.sum(A)\n{np.sum(A)}') 
print(f'Row sum: np.sum(A, axis=1)\n{np.sum(A, axis=1)}') 
print(f'Column sum: np.sum(A, axis=0)\n{np.sum(A, axis=0)}')

np.sum(A)
4062
Row sum: np.sum(A, axis=1)
[1806 2256]
Column sum: np.sum(A, axis=0)
[909 869 644 677 963]


In [5]:
#2-2)
print(f'np.mean(A)\n{np.mean(A)}') 
print(f'Row mean: np.mean(A, axis=1)\n{np.mean(A, axis=1)}') 
print(f'Column mean: np.mean(A, axis=0)\n{np.mean(A, axis=0)}')

np.mean(A)
406.2
Row mean: np.mean(A, axis=1)
[361.2 451.2]
Column mean: np.mean(A, axis=0)
[454.5 434.5 322.  338.5 481.5]


In [6]:
#3)
mu = 5
sigma = 1
np.random.seed(12345)
sample1 = normal(loc=mu, scale=sigma, size=5)
sample2 = normal(loc=mu, scale=sigma, size=10)
sample3 = normal(loc=mu, scale=sigma, size=100)
sample4 = normal(loc=mu, scale=sigma, size=1000)

#3-1)
mean1 = sample1.mean()
mean2 = sample2.mean()
mean3 = sample3.mean()
mean4 = sample4.mean()
print(mean1-mu)
print(mean2-mu)
print(mean3-mu)
print(mean4-mu)


0.23296944633426442
0.5351306762548669
-0.05428410321862476
-0.00917099351412709


In [7]:
#3-2)
sd1 = sample1.std()
sd2 = sample2.std()
sd3 = sample3.std()
sd4 = sample4.std()
print(sd1-sigma)
print(sd2-sigma)
print(sd3-sigma)
print(sd4-sigma)

-0.05735858977085073
-0.22773291720762479
0.03515818170006524
-0.027448979500193427


### Numpy 성능 비교

In [8]:
#4)
N = 300 # 행, 열의 크기
matrix_A = np.array(rand(N, N))
matrix_B = np.array(rand(N, N))
matrix_C = np.zeros((N,N))

In [9]:
#4-1)
start = time.time()

for i in range(N):
    for j in range(N):
        for k in range(N):
            matrix_C[i][j] += matrix_A[i][k] * matrix_B[k][j]
            
print('Time with Python = %.2f[sec]' % float(time.time() - start))

Time with Python = 25.91[sec]


In [10]:
#4-2)
start = time.time()

matrix_C = np.dot(matrix_A, matrix_B)

print('Time with Numpy = %.2f[sec]' % float(time.time() - start))

Time with Numpy = 0.01[sec]


In [11]:
#5)
np.arange(0,10,1)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
np.linspace(0,10,11)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [13]:
#6)
np.eye(N=3, M=3, k=1)

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [14]:
np.eye(N=3, M=3, k=-1)

array([[0., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.]])

In [15]:
#7)
np.diag(np.arange(0,20,5))

array([[ 0,  0,  0,  0],
       [ 0,  5,  0,  0],
       [ 0,  0, 10,  0],
       [ 0,  0,  0, 15]])

### 행렬의 곱

In [16]:
#8)
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])

#8-1)
print(np.dot(A,B), "\n")
print(np.inner(A,B))

[[19 22]
 [43 50]] 

[[17 23]
 [39 53]]


In [17]:
#8-2)
C = A.dot(B) 
print("A*B =", C) 

C = np.dot(A,B) 
print("A*B =", C) 

C =  np.mat(A) * np.mat(B) 
print("A*B =", C) 

C =  np.matmul(A,B) 
print("A*B =", C)

A*B = [[19 22]
 [43 50]]
A*B = [[19 22]
 [43 50]]
A*B = [[19 22]
 [43 50]]
A*B = [[19 22]
 [43 50]]


In [18]:
#9)
A = np.array([[1, 5, 3], [4, 6, 6], [3, 8, 9]]) 
B = np.array([[1, 5, 3, 4], [4, 5, 7, 8], [7, 8, 9, 3]]) 
M =  np.matmul(A,B) 
print("M=", M)

M= [[ 42  54  65  53]
 [ 70  98 108  82]
 [ 98 127 146 103]]


### 행렬의 전치(transpose)

In [19]:
#10)
A = np.array([[1, 3, 7, 2], [5, 8, -9, 0], [6, -7, 11, 12]])
print("A="); print(A)

A=
[[ 1  3  7  2]
 [ 5  8 -9  0]
 [ 6 -7 11 12]]


In [20]:
Atr= np.transpose(A)
print("Transpose of A="); print(Atr)

Transpose of A=
[[ 1  5  6]
 [ 3  8 -7]
 [ 7 -9 11]
 [ 2  0 12]]


### 행렬식(determinant)

In [21]:
#11)
import numpy.linalg as la

A = np.array([[1, 2], [3, 4]])
Adet= la.det(A)
print(Adet)

-2.0000000000000004


In [22]:
B = np.array([[-1, 3, 0], [2, 1, -5], [1, 4, -2]])
Bdet= la.det(B)
print(Bdet)

-21.00000000000001


### 역행렬

In [23]:
#12)
Ainv = la.inv(A)
print(Ainv)

[[-2.   1. ]
 [ 1.5 -0.5]]


In [24]:
Binv = la.inv(B)
print(Binv)

[[-0.85714286 -0.28571429  0.71428571]
 [ 0.04761905 -0.0952381   0.23809524]
 [-0.33333333 -0.33333333  0.33333333]]


### 고유값

In [25]:
#13)
Aeig, v = la.eig(A)
print(Aeig)

[-0.37228132  5.37228132]


### 선형방정식

In [26]:
#14)
# x1 + 3*x2 = 7
# 2*x1 + 5*x2 = 12
A = np.array([[1,3],[2,5]])
b = np.array([7,12]).reshape(2,1)

#14-1)
x = np.matmul(la.inv(A), b)
print(x)

[[1.]
 [2.]]


In [27]:
#14-2)
np.linalg.solve(A,b)

array([[1.],
       [2.]])

### 특이행렬

In [28]:
#15)
from numpy.linalg import LinAlgError

def check_sing(A): 
  print('A = ') 
  print(np.array(A)) 
  try: 
    np.linalg.inv(A) 
  except LinAlgError as e: 
    print(e)
  else: 
    print('Not singular!') 
  print()

In [29]:
#15-1)
check_sing([[0, 0], [0, 0]])

A = 
[[0 0]
 [0 0]]
Singular matrix



In [30]:
#15-2)
check_sing(np.eye(4))

A = 
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
Not singular!



In [31]:
#15-3)
for j in range(10): 
  check_sing(np.random.randn(3, 3))

A = 
[[ 0.05485407  0.27890458 -0.07399833]
 [-1.43190271  1.44352613 -0.3511314 ]
 [ 0.13450537 -1.2288247  -0.51980169]]
Not singular!

A = 
[[ 0.6499399  -0.57789408  0.41071036]
 [-0.35368101 -1.00035163  0.97099344]
 [ 1.20224816  0.50764601  0.05730023]]
Not singular!

A = 
[[-0.33669798 -0.52721077  0.45665021]
 [-0.31979101 -2.77109361  0.06819525]
 [-1.27561849 -1.06213929  1.44407006]]
Not singular!

A = 
[[ 0.1842034   0.50735908  0.5096157 ]
 [ 2.14834713 -0.82490663 -0.34259836]
 [ 0.76028404 -1.00442329  0.87987617]]
Not singular!

A = 
[[-1.20168646 -0.01021002 -0.31519027]
 [ 0.77320193 -1.17813767  0.87912274]
 [ 0.89640093  0.13341222  0.06517489]]
Not singular!

A = 
[[-0.7736675  -1.0141297  -0.95165379]
 [-0.00267569 -0.28753705  1.11348616]
 [ 0.54983845  1.98970402 -2.04811513]]
Not singular!

A = 
[[ 0.06679469 -0.01812925 -0.41390759]
 [ 0.35732265 -0.33561651 -1.34763773]
 [-0.27920661  0.51795599  0.12649928]]
Not singular!

A = 
[[-0.98282672 -0.38656305 -0.